apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-operator
  labels:
spec:
  selector:
    matchLabels:
  replicas: 1
  template:
    metadata:
      labels:
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: elasticsearch-operator
      containers:
      - command:
        - elasticsearch-operator
        ports:
        - containerPort: 8080
          name: http
        image: quay.io/openshift-logging/elasticsearch-operator:latest
        name: elasticsearch-operator
        imagePullPolicy: IfNotPresent
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.annotations['olm.targetNamespaces']
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: OPERATOR_NAME
            value: "elasticsearch-operator"
          - name: RELATED_IMAGE_OAUTH_PROXY
            value: "quay.io/openshift/origin-oauth-proxy:latest"
          - name: RELATED_IMAGE_ELASTICSEARCH_PROXY
            value: "quay.io/openshift-logging/elasticsearch-proxy:1.0"
          - name: RELATED_IMAGE_ELASTICSEARCH
            value: "quay.io/openshift-logging/elasticsearch6:6.8.1"
          - name: RELATED_IMAGE_KIBANA
            value: "quay.io/openshift-logging/kibana6:6.8.1"
          - name: RELATED_IMAGE_CURATOR
            value: "quay.io/openshift-logging/curator5:5.8.1"
